server:
  port: 8021
  error:
    whitelabel:
      enabled: false

spring:
  application:
    name: erp
  profiles:
    active: 'local'
  h2:
    console.enabled: true
  mvc:
    throw-exception-if-no-handler-found: true
    view:
      prefix: /resources/templates/
      suffix: .html
    resources:
      add-mappings: false
    thymeleaf:
      cache: false
    main:
      web-application-type: servlet
